export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const POST_PRODUCT = "POST_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const GET_USERS = "GET_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const GET_ORDERS = "GET_ORDERS";
export const UPDATE_ORDER = "UPDATE_ORDER";

export const GET_ORDER_STATUS = "GET_ORDER_STATUS";

export const POST_NEWSLETTER = "POST_NEWSLETTER";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SUBCATEGORY_BY_CATEGORY = "GET_SUBCATEGORY_BY_CATEGORY";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const GET_PRODUCTS_BY_BRAND = "GET_PRODUCTS_BY_BRAND";

export const FILTER_BY_BRAND = "FILTER_BY_BRAND";
export const FILTER_BY_PRICE = "FILTER_BY_PRICE";
export const ORDER_BY_PRICE = "ORDER_BY_PRICE";
export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const CLEAN_SEARCH_RESULTS = "CLEAN_SEARCH_RESULTS";
export const GET_REVIEWS_BY = "GET_REVIEWS_BY";
export const SET_LOGGED_USER = "SET_LOGGED_USER";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const ADD_OR_REMOVE_QUANTITY_FROM_CART =
  "ADD_OR_REMOVE_QUANTITY_FROM_CART";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const ALL_FAVORITES_BY_USER = "ALL_FAVORITES_BY_USER";
export const ALL_CART_BY_USER = "ALL_CART_BY_USER";
export const CREATE_ORDER = "CREATE_ORDER";
export const ALL_ORDERS_BY_USER = "ALL_ORDERS_BY_USER";
export const GET_PAYPREFERENCES_BY_ID = "GET_PAYPREFERENCES_BY_ID";
export const GET_CARROUSEL = "GET_CARROUSEL";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const FILTER_BY = "FILTER_BY";
// Funciones sincrÃ³nicas

export const ADD_CART = "ADD_CART";
export const REMOVE_CART = "REMOVE_CART";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const CLEAN_CATEGORY_PRODUCTS = "CLEAN_CATEGORY_PRODUCTS";
export const CLEAN_FAVORITES = "CLEAN_FAVORITES";
export const CLEAN_PRODUCTS_BY_BRAND = "CLEAN_PRODUCTS_BY_BRAND";

export const GET_ALL_STATISTICS = "GET_ALL_STATISTICS";
//Faltan actions
