export const GET_ALL_PRODUCTS= 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_BY_ID= 'GET_PRODUCT_BY_ID';
export const POST_PRODUCT= 'POST_PRODUCT';
export const POST_NEWSLETTER = 'POST_NEWSLETTER';
export const GET_CATEGORIES= 'GET_CATEGORIES';
export const GET_PRODUCTS_BY_CATEGORY= 'GET_PRODUCTS_BY_CATEGORY';
export const FILTER_BY_BRAND= 'FILTER_BY_BRAND';
export const FILTER_BY_PRICE= 'FILTER_BY_PRICE';
export const ORDER_BY_PRICE= 'ORDER_BY_PRICE';
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const COMPLETE_PROFILE = 'COMPLETE_PROFILE';
export const GET_REVIEWS_BY = "GET_REVIEWS_BY";
export const STATUS_REGISTER = 'STATUS_REGISTER';
export const GET_NEW_REGISTERED_USER= 'GET_NEW_REGISTERED_USER';



// Funciones sincrónicas
export const ADD_CART= 'ADD_CART';
export const REMOVE_CART= 'REMOVE_CART';
export const ADD_FAVORITE= 'ADD_FAVORITE';
export const REMOVE_FAVORITE= 'REMOVE_FAVORITE';


//Faltan actions